name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
jobs:
    build-test-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r vw_challenge_cdk/requirements.txt
        - name: Lint and Test
          run: |
            flake8 vw_challenge_cdk tests
            pytest tests
        - name: Deploy CDK Stack
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-1'
          run: |
            cdk synth
            cdk deploy --require-approval never